// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiningIssueTracker.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MiningIssueTracker.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MiningIssueTracker.Api.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Crusher #3",
                            SiteId = 1,
                            Type = "Crusher"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Conveyor Belt #1",
                            SiteId = 1,
                            Type = "Conveyor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Drill Rig #2",
                            SiteId = 2,
                            Type = "Drill"
                        });
                });

            modelBuilder.Entity("MiningIssueTracker.Api.Models.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedTo")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("SiteId");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("MiningIssueTracker.Api.Models.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Welshpool, WA",
                            Name = "Site A"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Karratha, WA",
                            Name = "Site B"
                        });
                });

            modelBuilder.Entity("MiningIssueTracker.Api.Models.Equipment", b =>
                {
                    b.HasOne("MiningIssueTracker.Api.Models.Site", "Site")
                        .WithMany("Equipment")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("MiningIssueTracker.Api.Models.Issue", b =>
                {
                    b.HasOne("MiningIssueTracker.Api.Models.Equipment", "Equipment")
                        .WithMany("Issues")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MiningIssueTracker.Api.Models.Site", "Site")
                        .WithMany("Issues")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("MiningIssueTracker.Api.Models.Equipment", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("MiningIssueTracker.Api.Models.Site", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Issues");
                });
#pragma warning restore 612, 618
        }
    }
}
